spring:
  datasource:
    url : jdbc:mysql://localhost:3306/test
    username : root
    password : 1234
    driver-Class-Name : com.mysql.jdbc.Driver
  freemarker:
    request-context-attribute: req  #req访问request
    suffix: .ftl  #后缀名
    content-type: text/html
    enabled: true
    cache: false #缓存配置
    template-loader-path: classpath:/templates/ #模板加载路径 按需配置
    charset: UTF-8 #编码格式
    settings:
      number_format: '0.##'   #数字格式化，无小数点
  redis:
    database:  0
    host: 127.0.0.1
    port: 6379
    password: 123
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
  ##视图模型
  ##thymeleaf:
   ##prefix: classpath:/templates/
   ##suffix: .html
   ##cache: false
   ##encoding: utf-8
   ##content-type: text/html
   ##check-template-location: true
