
server:
  port: 80
spring:
#配置上传文件大小限制
  servlet:
    multipart:
      max-file-size: 30Mb
      max-request-size: 30Mb
  freemarker:
    request-context-attribute: req  #req访问request
    suffix: .ftl  #后缀名
    content-type: text/html
    enabled: true
    cache: false #缓存配置
    template-loader-path: classpath:/templates/ #模板加载路径 按需配置
    charset: UTF-8 #编码格式
    settings:
      number_format: '0.##' #数字格式化，无小数点
  profiles:
    active: prod

mybatis-plus:
  mapper-locations:  classpath*:/mapper/*Mapper.xml
  type-aliases-package: com.changex.blog.core.pojo
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl    #sql打印控制台
  global-config:
    db-config:
      logic-delete-value: 0
      logic-not-delete-value: 1
      id-type: auto
      field-strategy: not_empty
      table-underline: true

logging:
  config: classpath:logback-spring.xml
  path: /LOGS
